---
name: FrozenEconomy
version: 0.0.1
main: IcyEndymion004\FrozenEconomy\Loader
authors: [Pixelated Studios, IcyEndymion004]
api: 4.2.0
src-namespace-prefix: IcyEndymion004\FrozenEconomy
permissions:
  player.base.frozen.economy:
    default: true
    description: Allows Usage of all Basic Player Commands.
  admin.base.frozen.economy:
    default: false
    description: Allows Usage of all Admin Commands.
  owner.base.frozen.economy:
    default: false
    description: Allows Usage of GAME BREAKING COMMANDS WITH IN THE PLUGIN.
...
